[options]
admin_passwd = RuaFM@Admin2026
db_host = fm-odoo-db
db_port = 5432
db_user = odoo
db_password = odoo@rua2026
db_name = rua
addons_path = /opt/odoo/addons,/mnt/extra-addons
data_dir = /var/lib/odoo
http_port = 8069
proxy_mode = True
list_db = False
log_level = info
